pull_request_rules:
  - name: Automatic approve Renovate PRs (patch/minor)
    conditions:
      - author=renovate[bot]
      - label=automerge
    actions:
      review:
        type: APPROVE

  - name: Automatic merge Renovate PRs (patch/minor)
    conditions:
      - author=renovate[bot]
      - base=main
      - label=automerge
      - "#approved-reviews-by>=1"
      - check-success=Max TF pre-commit
      - check-success=Validate PR title
    actions:
      merge:
        method: squash

  - name: Automatic merge on approval
    conditions:
      - base=main
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash

  - name: Automatic merge on approval release
    conditions:
      - base=release
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
