name: Renovate

on:
  pull_request:
    branches:
      - main

jobs:
  renovate-config-check:
    name: "renovate:config"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Renovate Config
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
